# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango1', '0004_auto_20180213_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
